### ISSUE TITLE
Memory leak with Event Handlers

### ISSUE THREAD

**Issue by stefmorren** [TheHackerDev/GameOfLife#1]
Hello! 

I have found a Memory Leak in your application. When you start spamming the "New" button, you will get event handler leaks. I saw this in my memory management tool and then I did an analysis with dotMemory. 

 
![image](https://user-images.githubusercontent.com/24243510/32270223-4246a854-bef5-11e7-859d-63bccfefae4b.png)

**Comment by TheHackerDev** [comment]
Thanks for opening an issue, @stefmorren! Unfortunately, I haven't been maintaining this repository anymore, so this issue won't be fixed. If you'd like, you can submit a pull request to fix it. It's also just kind of a fun game, so I don't think it's necessarily critical to fix this at this time.

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))
